// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/vkuzmenkova/currency-rates/models"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetLastRate provides a mock function with given fields: ctx, _a1, base, currency_code
func (_m *Service) GetLastRate(ctx context.Context, _a1 uuid.UUID, base string, currency_code string) (models.CurrencyRate, error) {
	ret := _m.Called(ctx, _a1, base, currency_code)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRate")
	}

	var r0 models.CurrencyRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (models.CurrencyRate, error)); ok {
		return rf(ctx, _a1, base, currency_code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) models.CurrencyRate); ok {
		r0 = rf(ctx, _a1, base, currency_code)
	} else {
		r0 = ret.Get(0).(models.CurrencyRate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, _a1, base, currency_code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRateByUUID provides a mock function with given fields: ctx, _a1
func (_m *Service) GetRateByUUID(ctx context.Context, _a1 uuid.UUID) (models.CurrencyRate, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetRateByUUID")
	}

	var r0 models.CurrencyRate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.CurrencyRate, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.CurrencyRate); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(models.CurrencyRate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRate provides a mock function with given fields: ctx, _a1, base, currency_code
func (_m *Service) UpdateRate(ctx context.Context, _a1 uuid.UUID, base string, currency_code string) error {
	ret := _m.Called(ctx, _a1, base, currency_code)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, _a1, base, currency_code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
