server:
  host: localhost
  port: 8080
db:
  driver: postgres
  host: localhost
  port: 5432
  name: postgres
  user: habrpguser
  password: pgpwd4habr
  ssl_mode: disable
redis:
  host: localhost
  port: 6379
