basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: valentinakuzmenkova@gmail.com
    name: Valentina Kuzmenkova
  description: This is a sample server celler server.
  title: Swagger Currency Rate API
  version: "1.0"
paths: {}
swagger: "2.0"
